language: php
php:
  - 7.0
  - 5.6
  - 5.5
before_script:
    - pecl install libsodium
    - composer --no-interaction --no-progress install
    - composer show --installed
script: vendor/bin/phpunit
