imports:
  - resource: di.yml
  - resource: config.env.yml
  - resource: routes.yml

# environment independent parameters
parameters:
    application.id: 200001

    slim.hooks:
        slim.before: []
        slim.before.router:
            - 'slim.hook.routes'
